name = "telegram-backup-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "telegram-backup-bot-db"
database_id = "0c464c6c-b2e1-4cdf-b034-c2d93d611c83"
